//@ui5-bundle projectc/Component-preload.js
sap.ui.require.preload({
	"projectc/Component.js":function(){
sap.ui.define(["sap/ui/core/UIComponent","projectc/model/models"],(e,t)=>{"use strict";return e.extend("projectc.Component",{metadata:{manifest:"json",interfaces:["sap.ui.core.IAsyncContentCreation"]},init(){e.prototype.init.apply(this,arguments);this.setModel(t.createDeviceModel(),"device");this.getRouter().initialize()}})});
},
	"projectc/controller/App.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],e=>{"use strict";return e.extend("projectc.controller.App",{onInit(){}})});
},
	"projectc/controller/Main.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],e=>{"use strict";return e.extend("projectc.controller.Main",{onInit(){},clickMyButton(){let e=this.getView();let t=e.byId("myImage1");let s=e.byId("myImage2");let l=t.getVisible();t.setVisible(!l);s.setVisible(l);let o={on:"Toggle ON",off:"Toggle OFF"};let g=e.byId("myToggleButton");if(g.getPressed()){g.setPressed(false);sap.m.MessageToast.show(o.off);g.setText(o.off)}},toggleMyButton(){let e=this.getView();let t=e.byId("myToggleButton");let s=t.getPressed();let l={on:"Toggle ON",off:"Toggle OFF"};if(s){sap.m.MessageToast.show(l.on);t.setText(l.on)}else{sap.m.MessageToast.show(l.off);t.setText(l.off)}let o=e.byId("myImage1");let g=e.byId("myImage2");let i=o.getVisible();let a=g.getVisible();o.setVisible(s);g.setVisible(s)}})});
},
	"projectc/i18n/i18n.properties":'# This is the resource bundle for projectc\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=App Project C\n\n#YDES: Application description\nappDescription=An SAP Fiori application | From template\n#XTIT: Main view title\ntitle=App Project C',
	"projectc/manifest.json":'{"_version":"1.65.0","sap.app":{"id":"projectc","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.17.3","toolsId":"cb389838-1abb-4bd7-a494-b3602af82c44"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.135.0","libs":{"sap.m":{},"sap.ui.core":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"projectc.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","controlAggregation":"pages","controlId":"app","transition":"slide","type":"View","viewType":"XML","path":"projectc.view","async":true,"viewPath":"projectc.view"},"routes":[{"name":"RouteMain","pattern":":?query:","target":["TargetMain"]}],"targets":{"TargetMain":{"id":"Main","name":"Main"}}},"rootView":{"viewName":"projectc.view.App","type":"XML","id":"App","async":true}}}',
	"projectc/model/models.js":function(){
sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"projectc/view/App.view.xml":'<mvc:View controllerName="projectc.controller.App"\n    displayBlock="true"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"><App id="app"></App></mvc:View>',
	"projectc/view/Main.view.xml":'<mvc:View xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" controllerName="projectc.controller.Main"><Page id="page" title="{i18n>title}"><content><FlexBox\n            class="my-box__block"\n            direction="Row"\n            alignItems="Center"\n            gap="20px"><VBox\n                class="my-box__buttons"><Button class="my-button" text="Button" id="myButton" press="clickMyButton"/><ToggleButton class="my-toggle-button" text="Toggle Button" id="myToggleButton" press="toggleMyButton" activeIcon="sap-icon://accept"/></VBox><HBox\n                class="my-box__images"\n                gap="20px"><Image src="https://github.com/ashuksu/runes/blob/main/src/uploads/banner-2.jpg?raw=true" \n                    class="my-image" width="140px" height="140px" id="myImage1" alt="my Image 1"/><Image src="https://github.com/ashuksu/runes/blob/main/src/uploads/banner-1.jpg?raw=true" \n                    class="my-image" width="140px" height="140px" id="myImage2" alt="my Image 2" visible="false"/></HBox></FlexBox></content></Page></mvc:View>'
});
//# sourceMappingURL=Component-preload.js.map
